In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st

#### Задание 1
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):<br> zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]<br> ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]<br> Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy Полученные значения должны быть равны. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
cov = (zp*ks).mean() - zp.mean()*ks.mean()
cov

9157.839999999997

In [6]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [7]:
np.cov(zp, ks, ddof=0)/(zp.std()*ks.std())

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [8]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [23]:
turp = list(zip(zp, ks))
df = pd.DataFrame(turp, columns=['zp', 'ks'])
df.corr()


zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

#### Задание 2
Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [36]:
ar = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = len(ar) # Объем выборки
x = ar.mean() # Среднее выборочное
gamma = 0.95 # Доверительная вероятность
std_mis = st.sem(ar) # Стандартная ошибка среднего
st.t.interval(gamma,n-1, x, std_mis)

(110.55608365158724, 125.64391634841274)

#### Задание 3
Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [35]:
n = 27 # Объем выборки
x = 174.2 # Среднее выборочное
gamma = 0.95 # Доверительная вероятность
v = 25 # Дисперсия генерельной совокупности
std_mis = np.sqrt(v)/np.sqrt(n) # Стандартная ошибка среднего
st.norm.interval(gamma, x, std_mis)

(172.3140237765397, 176.08597622346028)